name: Build

on:
  workflow_dispatch: ~
  push:
    branches:
      - main
    paths:
      - src/**
      - package.json
      - pnpm-lock.yaml
      - Dockerfile
      - tsconfig.json

jobs:
  build:
    name: Build image and push onto dockerhub
    runs-on: ubuntu-latest
    steps:
      - uses: wdzeng/dockerhub@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  tag:
    name: Add tags to repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: version
        uses: wdzeng/version@v1
        with:
          prefix: v
      - name: Add tags
        run: |
          git tag -f ${{ steps.version.outputs.version }} main && \
          git push -f origin ${{ steps.version.outputs.version }}
